service: lyrically

provider:
  name: aws
  runtime: python3.6
  memorySize: 128
  deploymentBucket:
    name: boristane-lambdas-deployments
  region: eu-west-2
  logRetentionInDays: 7
  versionFunctions: false

package:
  exclude:
    - node_modules/**
    - .venv/**
    - .cache/**
    - .vscode/**

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-domain-manager

custom:
  wsgi:
    app: ./app/main.app
    packRequirements: false
  customDomain:
    domainName: lyrically.be
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: 'regional'

environment:
    GENIUS_TOKEN: ${ssm:/boristane/lyrically/genius/token}
    SPOTIFY_CLIENT_ID: ${ssm:/boristane/lyrically/spotify/client-id}
    SPOTIFY_REDIRECT_URI: "https://lyrically.be/lyrics"
    SPOTIFY_CLIENT_SECRET: ${ssm:/boristane/lyrically/spotify/client-id}


functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'